#ifndef ERROR_H
#define ERROR_H

#define TINY_EOF -1
#define TINY_UNEXPECTED_EOF -2
#define TINY_UNEXPECTED_TOKEN -3
#define TINY_INVALID_STRING -4
#define TINY_INVALID_STRING_X_NO_FOLLOWING_HEX_DIGITS -5
#define TINY_INVALID_NUMBER -6
#define TINY_EXPECT_SEMICOLON -7
#define TINY_EXPECT_LEFT_PARENTHESIS -8
#define TINY_EXPECT_RIGHT_PARENTHESIS -9
#define TINY_EXPECT_BEGIN -10
#define TINY_EXPECT_END -11
#define TINY_EXPECT_IDENTIFIER -12
#define TINY_EXPECT_STATEMENT -13
#define TINY_EXPECT_EXPRESSION -14
#define TINY_EXPECT_TYPE -15
#define TINY_EXPECT_COMMA -16
#define TINY_EXPECT_FUNC_VARS -17
#define TINY_UNTERMINATED_STRING_OR_CHARACTER -18
#define TINY_MAY_FUNC_CALL -100

#endif // ERROR_H